config/routes.rb
Rails.application.routes.draw do
  
 
  
  
  resource :session, only:[:new, :create, :destroy]
  get '/oturum_ac',       to: 'sessions#new',     as: :login
  delete '/oturum_kapat', to: 'sessions#destroy', as: :logout
  resource :session, only:[:new, :create, :destroy]
  get '/kaydol',          to: 'users#new',       as: :register
  get '/users/new',       to: redirect('/kaydol')
  get '/:id',             to: 'users#show',      as: :profile
  get '/:id/edit',        to: 'users#edit',      as: :edit_profile 
  resources :users, except: :index
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username,   presence:   true,
	  	                 uniqueness: { case_sensitive: false },
		                 length:     { in: 4..12 },
		                 format:     { with: /\A[a-zA-Z][a-zA-Z0-9_-]*\Z/ }
  validates :first_name, presence:   true
  validates :last_name,  presence:   true
  validates :email,      presence:   true,
	                 uniqueness: { case_sensitive: false },
                         email:      true
  validates :username,   presence:   true,
                        exclusion: { in: ['oturum_ac'] }
			            
  
  def name
  	"#{first_name} #{last_name}"
  end

  def to_param
  	username
  end

  def avatar_url
  	hash_value = Digest::MD5.hexdigest(email.downcase)
  	"http://www.gravatar.com/avatar/#{hash_value}?s=160"
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method  :signed_in?, :current_user
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    current_user
  end
  
  def login(user)
    session[:user_id] = user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:session][:username])

    if user && user.authenticate(params[:session][:password]) 
      login(user)
      redirect_to profile_path(user), notice: 'Oturum Açıldı.'
    else
      flash.now[:error] = "Kullanıcı adı/parola hatalı."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Oturumunuz sonlandırıldı.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :select_user, only: [:show, :edit, :update, :destroy]
  before_action :allowed?,    only: [:edit, :create, :destroy]
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	
  	if @user.save
      login(@user)
  	  redirect_to profile_path(@user), notice:'Aramıza hoş geldin.'
  	else
  		render :new
  	end
  end

  def show
  	@data = []

  	if params[:sayfa]
  	  render layout: 'profile', locals: {page: params[:sayfa]}
  	else
  	  render layout: 'profile', locals: {page: 'konular' }
  	end
  end

  def edit
    render layout: "profile"
  end

  def update
  	update_params = user_params
    if update_params.has_key?(:password)
  	  update_params.delete([:password, :password_confirmation])
  	end

    if @user.update(user_params)
  	  redirect_to profile_path(@user), notice: 'Profil bilgilerin güncellendi.'
  	else
  	  render :edit, layout: "profile"
  	end
  end

  def destroy
  	@user.destroy
  	redirect_to '/'
  end 


  private
  

  def user_params
  	params.require(:user).permit!
  end

  def select_user
  	@user = User.find_by_username(params[:id])
  end

  def allowed?
    user = select_user

    unless current_user == user
      redirect_to profile_path(user), alert: 'Bunu yapmaya yetkiniz yok!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_error_message(message = 'Geçerli bir değer giriniz')
  	['<small class="error">', message, '</small>'].join.html_safe
  end

  def flash_class(type)
  	{ notice: 'succes', alert: 'info', error: 'warning '}[type]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div data-alert class="alert-box <%= flash_class(type) %>">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
<% end %>

app/views/layouts/_top_bar.html.erb
 <div class="contain-to-grid">
  <nav class="top-bar" data-topbar > 
      <ul class="title-area">
        <li class="name">
  	      <h1><a href="/">Rails on Forum</a></h1>
	      </li>
   	 </ul>
    <section class="top-bar-section">
      <ul class="right">
        <% if signed_in? %>
          <li class="has-dropdown">
            <a href="#"><%= current_user.name %></a>
            <ul class="dropdown">
              <li><%= link_to "Profilimi Görüntüle", profile_path(current_user)%></li>
              <li><%= link_to "Oturumu Kapat", logout_path, method: :delete %></li>
            </ul>
          </li>
        
        <% else %>
	        <li class="divider"></li>
	        <li><%=link_to "Kaydol", register_path %></li> 
	        <li class="divider"></li>
	        <li><a href="#">Oturum Aç</a></li> 
          <li class="divider"></li>
      <% end %>
      </ul>
    </section>
  </nav>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/top_bar' %>
    <div class="row">
       <%= render 'layouts/flash_messages' %> 
       <%= content_for?(:content) ? yield(:content) : yield %>
     </div>
     
     <%=javascript_include_tag "application" %>  
 </body>
</html>

app/views/layouts/profile.html.erb
<% content_for(:content) do %>
<div class="row">
  <div class="large-12 columns">
    <div class="large-2 columns">
      <%= image_tag @user.avatar_url, class: 'profile-image' %>
    </div>

    <div class="large-10 columns">
      <h2><%= @user.name %><h2>
      <p><%= @user.email %></p>
      <div class="button-bar">
        <ul class="button-group radius">
          <li><%= link_to "Konular", profile_path(@user, sayfa: 'konular'),
          							 class: 'small button secondary' %></li>
          <li><%= link_to "Yorumlar", profile_path(@user, sayfa: 'yorumlar'),
                         class: 'small button secondary' %></li>
          <% if current_user == @user %>  
            <li><%= link_to "Profilimi düzenle.", edit_profile_path(@user),
          							            class: 'small button secondary' %></li>
            <li><%= link_to "Hesabımı sil.", @user,
                                    method: :delete,
                                    data: {confirm: 'Hesabınızı silmek istediğinize..?'}, 
                                    class: 'small button alert' %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <%= yield(:profile_content) %>
  </div>
</div>
<% end %>
<%= render template: "layouts/application" %>

app/views/users/_form.html.erb
<%= form_for @user, data: { abide: ''} do |form| %>
  <% if @user.errors.any? %>
    <div class="row panel callout radius">
      <p>Aşağıdaki hataları düzeltip, tekrar deneyiniz.</p>
      <ul class="square">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="large-6 columns">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, required: true,
      									 pattern: :alpha %>
    <%= show_error_message %>
    </div>
    <div class="large-6 columns">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, required: true,
       									pattern: :alpha %>
      <%= show_error_message %>   	
    </div>

    <div class="large-12 columns">
      <%= form.label :username %>
      <%= form.text_field :username, required: true,
      							      pattern: :alpha %>
      <%= show_error_message %>
    </div>

    <div class="large-12 columns">
      <%= form.label :email %>
      <%= form.email_field :email, required: true,
      							      pattern: :email  %>
    <%= show_error_message %>  
    </div>

  <% if params[:action] == 'new' || params[:action] == 'create' %>
    <div class="large-6 columns">
      <%= form.label :password %>
      <%= form.password_field :password, required: true %>
    <%= show_error_message %>   
    </div>
    <div class="large-6 columns">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, required: true %>
    <%= show_error_message %>      
    </div>
    <% end %>
    <div class="large-12 columns">
      <%= form.submit class: 'medium button right' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= content_for(:profile_content) do %>
  <div class="large-12 columns">
    <h2>Profilimi Düzenle</h2>
    <%= render 'form' %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="large-7 medium-6 small-12 columns">
    <h2>Aramıza katılın!</h2>
    <%= render 'form' %>
  </div>
  <div class="large-5 medium-6 columns side-panel hide-for-small">
    <h3>Buralarda yeni misin?</h3>
    <p>O halde; hemen bir hesap oluştur ve bu büyük aileye katıl!</p>
    <ul>
      <li>Takıldığın konularla ilgili sorular sor.</li>
      <li>Diğerlerinin sorularını cevapla.</li>
      <li>İlgi alanlarını takip et ve tartışmalara dahil ol.</li>
    </ul>

    <p class="lead">
      Öğrenirken, öğretmek için yandaki formu doldurarak başlayabilirsin.
    </p>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:profile_content) do %>
  <h2><%= page.capitalize %></h2>

  <% if @data.blank? %>
    <p>Kullanıcıya ait <%= page %> bulunmamaktadır.</p>
  <% else %>
    <% @data.each do |data| %>
      <div><%= data %></div>
    <% end %>
  <% end %>
<% end %>